### ISSUE TITLE
提示抢到了，但是秀动APP打开订单啥都木有

### ISSUE THREAD

**Issue by Yancey597** [marunrun/showstart-checkout#10]
![image](https://user-images.githubusercontent.com/46004197/177702876-c6770bbc-5685-4fac-aef9-7d9e5766b747.png)

**Comment by marunrun** [comment]
你随便搜一个演出 购票试试呢。  我购票的逻辑好像也没改啊，昨天我还试过了。

**Comment by Yancey597** [comment]
奇怪了，随便找了一个演出确实是可以购买的，会不会是抢票逻辑不太一样呢，之前也出现过提示抢到但是订单里面木有

**Comment by marunrun** [comment]
> 奇怪了，随便找了一个演出确实是可以购买的，会不会是抢票逻辑不太一样呢，之前也出现过提示抢到但是订单里面木有

我是调用了秀动的下单接口 然后再调下单结果接口， 如果下单结果的接口成功了 我就会提示抢票成功。 
有可能是秀动接口调用成功了，但实际抢票失败了。 

这种情况我还没碰到过， 我有空的话会加上更详细的提示。

**Comment by marunrun** [comment]
建议抢票失败后 可以用那个捡漏。

其实我自己用定时抢票的成功率也很低，估计抢的人还是太多了，大部分都是捡漏成功的。

**Comment by Yancey597** [comment]
嗯嗯，辛苦啦

**Comment by Fengbujue2783** [comment]
好像是因为整点抢购人数过多所以系统卡顿导致的 整点抢到的票经常要过期了才显示出来
