### ISSUE TITLE
请问这是什么情况呀

### ISSUE THREAD

**Issue by jxx-sixhh** [marunrun/showstart-checkout#11]
![1657260958078](https://user-images.githubusercontent.com/85923287/177928688-7d8a6d2c-cf4b-4638-961a-ffabe8b18981.jpg)

**Comment by marunrun** [comment]
网络请求错误 初始化token错误了。 重新打开应该就可以了吧

**Comment by jxx-sixhh** [comment]
谢谢哥 确实解决了
我刚刚在蹲捡漏然后出现这个问题怎么办呜呜
![3b7e6f9559e1d7356d65a45290ee0f2](https://user-images.githubusercontent.com/85923287/177931177-52710def-9bfd-453c-8a9a-e5073d2b9d42.png)

**Comment by marunrun** [comment]
这个就是秀动的限制了，下单被限流 没办法

**Comment by jxx-sixhh** [comment]
好的谢谢大哥
