### ISSUE TITLE
请问这个怎么处理呢

### ISSUE THREAD

**Issue by jxx-sixhh** [marunrun/showstart-checkout#12]
![1b33b8af203b14d0ad58a994295d68c](https://user-images.githubusercontent.com/85923287/179509352-6b15287b-7263-46d1-b9c7-35a21d777ece.jpg)

**Comment by marunrun** [comment]
这个是捡漏出现的吧.  我已经改了捡漏的频率  秀动那边对接口请求速率做了限制

**Comment by marunrun** [comment]
已经发了新的release包  你可以重新下载试试

**Comment by jxx-sixhh** [comment]
谢谢大哥
