### ISSUE TITLE
请问出现这个错误如何处理

### ISSUE THREAD

**Issue by 15906740136** [marunrun/showstart-checkout#13]
6点钟开票，5点钟登录成功开启捡漏。到6点时候就出现这个异常。
图片无法添加，这里简单描述内容。
异常类型：NullReferenceException
堆栈在：form1.cs行号716

**Comment by marunrun** [comment]
跟这个一样 #12

**Comment by marunrun** [comment]
可以下载新的release包  捡漏已经调低频率
