### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by 3151241461** [marunrun/showstart-checkout#17]
README里可以加个运行需要的环境吗，小白（我）不知道怎么打开www

**Comment by marunrun** [comment]
> README里可以加个运行需要的环境吗，小白（我）不知道怎么打开www

讲道理应该 vscode 打开就行了，会自动下一些依赖之类的东西  

我其实对于c# 也不是很了解 (⊙_⊙)  我会抽空看一下的

**Comment by 971814971** [comment]
小白表示不知道怎么用，方便加上简易教程？

**Comment by marunrun** [comment]
> 小白表示不知道怎么用，方便加上简易教程？

可以看下[readme](https://github.com/marunrun/showstart-checkout) 里的使用说明  软件操作也不多的。

**Comment by 971814971** [comment]
是不知道怎么编译或调试这代码
