### ISSUE TITLE
[question] encrypt

### ISSUE THREAD

**Issue by ronething** [marunrun/showstart-checkout#2]
- 请教下大佬是如何准确逆向分析到下单逻辑的？

例如接口请求体加密逻辑等。

**Comment by marunrun** [comment]
> * 请教下大佬是如何准确逆向分析到下单逻辑的？
> 
> 例如接口请求体加密逻辑等。

@ronething   

https://blog.marun.run/android-ni-xiang-360-jia-gu-apkfrida-hook-java-dai-ma
 之前写过一个文章稍加记录。

一开始我只是用来抓包，抓到一些接口，然后根据接口的API找到调用的地方。

其实只要逆向成功了，剩下的就是时间问题而已，中间也是一路摸索过来的。

**Comment by ronething** [comment]
感谢回复，看来需要进行 app 的逆向，网页版 js 混淆严重，只能看出大概，请求体以及加密逻辑虽然能定位到但是看起来很痛苦。

**Comment by ronething** [comment]
值得一提的是，目前秀动貌似已经修改了部分逻辑，此项目的某些用到的 key 可能需要进行更新，对应请求体可能也需要进行更新。(对 c# 不熟悉，晚些时候再看看如何调试这个项目。

**Comment by marunrun** [comment]
> 值得一提的是，目前秀动貌似已经修改了部分逻辑，此项目的某些用到的 key 可能需要进行更新，对应请求体可能也需要进行更新。(对 c# 不熟悉，晚些时候再看看如何调试这个项目。

我这个项目已经很久没更新了， 其实参考意义已经不大了。因为秀动更新很频繁，我完全跟不上他的更新速度😂

关于[自动滑块](https://github.com/marunrun/showstart-checkout/blob/2ca0f08f8769a88f71da8a9faaa90dd828f38b3a/checkout/Res/slide.js?_pjax=%23js-repo-pjax-container%2C+.context-loader-container%2C+%5Bdata-pjax-container%5D#L58)，这里我自己的服务已经停掉了。

如果你需要自动滑块的话，可以自己部署一个服务：https://github.com/omigo/crack-slide-captcha

emm 其他的我自己也不太清楚了，不过我记得我最后逆向的秀动app的时候，app代码也已经做了混淆😷

**Comment by ronething** [comment]
不过我觉得主要的问题其实还是下单和加密逻辑，其他前置的步骤应该是不难解决的。
