### ISSUE TITLE
抢票失败后重新抢票的间隔

### ISSUE THREAD

**Issue by softwarefly** [marunrun/showstart-checkout#21]
10:26:43.369  {"state":"order025","success":false,"msg":"库存不足，无法下单"}
10:26:43.370  全价票抢票失败：库存不足，无法下单 order025
10:26:44.173  {"status":200,"state":"1","result":{"sessions":[{"sessionName":"成都站","sessionId":3018630,"isConfirmedStartTime":1,"ticketList":[{"ticketId":"54ef35c43e59fc601e666488e63b811a","ticketType":"全价票"
10:26:44.325  {"state":"orderLimit001","success":false,"msg":"下单速度过快,稍后重试"}
10:26:44.326  全价票抢票失败：下单速度过快,稍后重试 orderLimit001

抢票失败后，重新尝试的时间间隔感觉是否可以调整一下，间隔稍长一些，感觉触发了下单速过快的警告，容易错过票

**Comment by softwarefly** [comment]
软件做的很不错，可以在README中放个收款码，方便给你买杯咖啡~

**Comment by marunrun** [comment]
> 软件做的很不错，可以在README中放个收款码，方便给你买杯咖啡~

底部已经放了。 感谢😀
