### ISSUE TITLE
抢购成功提醒功能bug

### ISSUE THREAD

**Issue by softwarefly** [marunrun/showstart-checkout#22]
通知配置中钉钉群机器人URL输入框长度不够，无法保存完整的access_token，点击测试通知会自动退出

点击保存配置或者测试通知后最好能能够返回一个结果框更好~

**Comment by marunrun** [comment]
> 通知配置中钉钉群机器人URL输入框长度不够，无法保存完整的access_token，点击测试通知会自动退出
> 
> 
> 
> 点击保存配置或者测试通知后最好能能够返回一个结果框更好~


测试通知有把返回结果通过消息框的方式弹出 

自动退出是什么情况 有错误信息之类的吗
我有做全局异常捕获的 应该会有日志跟弹窗

**Comment by softwarefly** [comment]
没有日志和弹窗，可能是URL框无法保存完整信息吧

**Comment by marunrun** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/35883111/180699069-9d250b6d-1311-489e-a947-244fed275019.png">



> 没有日志和弹窗，可能是URL框无法保存完整信息吧

我这边url框没有做限制 而且有弹窗的。 你要不试试重新下载release包

**Comment by softwarefly** [comment]
> 

ok，我再试试

**Comment by Yancey597** [comment]
建议增加本地响铃功能，刚刚捡到漏了结果过期了

**Comment by marunrun** [comment]
> 建议增加本地响铃功能，刚刚捡到漏了结果过期了

win10有通知的  响铃是指播放音乐吗？    最新版有邮件通知的  邮件可以绑定微信啥的 通知会比较方便的
