### ISSUE TITLE
提示抢购成功但没有订单

### ISSUE THREAD

**Issue by spbcu** [marunrun/showstart-checkout#24]
捡漏功能提示成功，没有生成订单，但停止了捡漏，需要手动再次开启
日志如下：
20:12:16.711  {"success":true,"msg":"","state":1,"result":"pending"}
20:12:16.725  VIP票抢票成功: pending

**Comment by marunrun** [comment]
> 捡漏功能提示成功，没有生成订单，但停止了捡漏，需要手动再次开启
> 
> 日志如下：
> 
> 20:12:16.711  {"success":true,"msg":"","state":1,"result":"pending"}
> 
> 20:12:16.725  VIP票抢票成功: pending


OK 周末我会修复一下这个问题的
