### ISSUE TITLE
最新版点击购票报错 win11环境

### ISSUE THREAD

**Issue by division1985** [marunrun/showstart-checkout#27]
![image](https://user-images.githubusercontent.com/51917901/187031862-efa8ae0a-b1c9-43fd-b00a-8f39b1f3b570.png)

**Comment by marunrun** [comment]
🆗 可以先用旧版 我一会儿把新版删一下

**Comment by division1985** [comment]
另外昨天用旧版 , 一开始测试邮箱通知测试可以发送邮件, 后面就不行了. 配置了下钉钉助手 , 也发送不了。现在一点开消息通过之配置就闪退。![222222](https://user-images.githubusercontent.com/51917901/187032072-3d0c17a3-cb31-47f9-b5bb-aa6fe091598c.png)

**Comment by division1985** [comment]
> 另外昨天用旧版 , 一开始测试邮箱通知测试可以发送邮件, 后面就不行了. 配置了下钉钉助手 , 也发送不了。现在一点开消息通过之配置就闪退。![222222](https://user-images.githubusercontent.com/51917901/187032072-3d0c17a3-cb31-47f9-b5bb-aa6fe091598c.png)

昨天的旧版指得是今日新版的上一个版本。

**Comment by marunrun** [comment]
我这边测了一下 消息通知没什么问题啊.  你点那个测试通知有报错吗 还是什么?

**Comment by division1985** [comment]
> 我这边测了一下 消息通知没什么问题啊. 你点那个测试通知有报错吗 还是什么?

程序闪退了

**Comment by marunrun** [comment]
> > 我这边测了一下 消息通知没什么问题啊. 你点那个测试通知有报错吗 还是什么?
> 
> 程序闪退了

一般来说 程序崩溃了应该也会有日志的.  没有日志的话 我这边也找不到错误原因, 也没有办法帮到你.

**Comment by marunrun** [comment]
新的再试下购票 我这边测的没问题了.

**Comment by division1985** [comment]
> 新的再试下购票 我这边测的没问题了.

![image](https://user-images.githubusercontent.com/51917901/187033457-0f6fad1a-b10f-4042-8a7f-eeffd9ec0ec2.png)
新版购票成功后，发送邮件报错了。
1.08版本我刚刚重新解压了，测试了下发送邮件是可以的。只是我不能配置钉钉的，一配置，点开通知配置会闪退。闪退后日志文件没有异常信息。

**Comment by softwarefly** [comment]
同样配置了钉钉机器人，测试直接闪退，且日志无记录
