### ISSUE TITLE
关于消息通知配置出错

### ISSUE THREAD

**Issue by liudaye1** [marunrun/showstart-checkout#28]
![微信图片_20221004170114](https://user-images.githubusercontent.com/114988091/193779441-34b44e6e-b226-4475-a12d-2e5f22051df4.png)
1..08版本测试邮件通知时，会报上面这个错误

**Comment by abcljxshfand** [comment]
+1 请问如何使用邮件通知功能？

**Comment by marunrun** [comment]
请确认SMTP账号密码没有配置错误 。SMTP 的账号密码不是邮箱账号密码 具体的可以百度一下对应的邮箱SMTP设置。
