### ISSUE TITLE
你好 我想问下这个软件还维护吗，如果自己想要继续开发，需要学习哪些知识呢。 

### ISSUE THREAD

**Issue by lemonness** [marunrun/showstart-checkout#3]

**Comment by Wangxiaohuo0903** [comment]
同问同问，今天没抢到票气死了，准备学习如何写抢票软件呜呜呜

**Comment by lemonness** [comment]
> 

你是哪啊，抢啥的票，留个邮箱吗

**Comment by Wangxiaohuo0903** [comment]
抢秀动的票，在网上后来找到一个python脚本，但是大佬你的我完全看不懂，我看好像你把验证码滑动都解决了，现在非常好奇大佬是从哪学的！

从 Windows 版邮件发送

发件人: Young
发送时间: 2022年3月7日 17:04
收件人: marunrun/showstart-checkout
抄送: Wangxiaohuo0903; Comment
主题: Re: [marunrun/showstart-checkout] 你好=?UTF-8?Q?_=E6=88=91=E6=83=B3=E9=97=AE=E4=B8=8B=E8=BF=99=E4=B8=AA=E8=BD=AF=E4=BB=B6=E8=BF=98=E7=BB=B4=E6=8A=A4=E5=90=97=EF=BC=8C=E5=A6=82=E6=9E=9C=E8=87=AA=E5=B7=B1=E6=83=B3=E8=A6=81=E7=BB=A7=E7=BB=AD=E5=BC=80=E5=8F=91=EF=BC=8C=E9=9C=80=E8=A6=81=E5=AD=A6=E4=B9=A0=E5=93=AA=E4=BA=9B=E7=9F=A5=E8=AF=86=E5=91=A2=E3=80=82?==?UTF-8?Q?__=28Issue_#3=29?=

你是哪啊，抢啥的票，留个邮箱吗
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lemonness** [comment]
> 抢秀动的票，在网上后来找到一个python脚本，但是大佬你的我完全看不懂，我看好像你把验证码滑动都解决了，现在非常好奇大佬是从哪学的！ 从 Windows 版邮件发送 发件人: Young 发送时间: 2022年3月7日 17:04 收件人: marunrun/showstart-checkout 抄送: Wangxiaohuo0903; Comment 主题: Re: [marunrun/showstart-checkout] 你好=?UTF-8?Q?_=E6=88=91=E6=83=B3=E9=97=AE=E4=B8=8B=E8=BF=99=E4=B8=AA=E8=BD=AF=E4=BB=B6=E8=BF=98=E7=BB=B4=E6=8A=A4=E5=90=97=EF=BC=8C=E5=A6=82=E6=9E=9C=E8=87=AA=E5=B7=B1=E6=83=B3=E8=A6=81=E7=BB=A7=E7=BB=AD=E5=BC=80=E5=8F=91=EF=BC=8C=E9=9C=80=E8=A6=81=E5=AD=A6=E4=B9=A0=E5=93=AA=E4=BA=9B=E7=9F=A5=E8=AF=86=E5=91=A2=E3=80=82?==?UTF-8?Q?__=28Issue_#3=29?= 你是哪啊，抢啥的票，留个邮箱吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

我也是在学，这个仓库不是我的，我还在看代码学习中。

**Comment by lemonness** [comment]
> 抢秀动的票，在网上后来找到一个python脚本，但是大佬你的我完全看不懂，我看好像你把验证码滑动都解决了，现在非常好奇大佬是从哪学的！ 从 Windows 版邮件发送 发件人: Young 发送时间: 2022年3月7日 17:04 收件人: marunrun/showstart-checkout 抄送: Wangxiaohuo0903; Comment 主题: Re: [marunrun/showstart-checkout] 你好=?UTF-8?Q?_=E6=88=91=E6=83=B3=E9=97=AE=E4=B8=8B=E8=BF=99=E4=B8=AA=E8=BD=AF=E4=BB=B6=E8=BF=98=E7=BB=B4=E6=8A=A4=E5=90=97=EF=BC=8C=E5=A6=82=E6=9E=9C=E8=87=AA=E5=B7=B1=E6=83=B3=E8=A6=81=E7=BB=A7=E7=BB=AD=E5=BC=80=E5=8F=91=EF=BC=8C=E9=9C=80=E8=A6=81=E5=AD=A6=E4=B9=A0=E5=93=AA=E4=BA=9B=E7=9F=A5=E8=AF=86=E5=91=A2=E3=80=82?==?UTF-8?Q?__=28Issue_#3=29?= 你是哪啊，抢啥的票，留个邮箱吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

这个仓库不是我的，我也是非常想请教一下本仓库的作者。

**Comment by marunrun** [comment]
我是逆向了秀动的APP 然后抓包

需要了解一定的逆向 抓包的知识
然后剩下的就很简单了 就是自己去请求秀动的接口

说白了就是写一个软件 可以自动请求秀动的接口就ok 了

**Comment by marunrun** [comment]
新版修复了 可参考
