### ISSUE TITLE
我已经选择了邮寄地址，但还是提示请选择收货地址，请问如何解决

### ISSUE THREAD

**Issue by liyvhang** [marunrun/showstart-checkout#37]

**Comment by liyvhang** [comment]
![c14dcd3f19861366e8561f7cba78a6b](https://user-images.githubusercontent.com/44460901/220550798-7907e2cb-b5dc-46a2-9cf9-c7ee4a6858de.png)

**Comment by marunrun** [comment]
https://github.com/marunrun/showstart-checkout/releases/tag/untagged-cac2c49dada11d96be51

如果你是mac，你可以在上面那个链接下一个新版的


如果你是Windows 那么建议你使用1.x版本。

**Comment by liyvhang** [comment]
> https://github.com/marunrun/showstart-checkout/releases/tag/untagged-cac2c49dada11d96be51
> 
> 如果你是mac，你可以在上面那个链接下一个新版本的
> 
> 如果你是 Windows 那么建议你使用 1.x 版本。

测试成功了，感谢大佬，终于不用被那些黄牛恶心了

**Comment by marunrun** [comment]
> > https://github.com/marunrun/showstart-checkout/releases/tag/untagged-cac2c49dada11d96be51
> > 如果你是mac，你可以在上面那个链接下一个新版本的
> > 如果你是 Windows 那么建议你使用 1.x 版本。
> 
> 测试成功了，感谢大佬，终于不用被那些黄牛恶心了

如果你是Windows 那么还是推荐使用1.x版本，  那个版本应该用的人多一点，问题可能会少一点。
