### ISSUE TITLE
macpro m1 12.6.3 打开报错

### ISSUE THREAD

**Issue by sheng3233836** [marunrun/showstart-checkout#38]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/23568201/221830527-0f27ab4e-fe06-46d1-b10a-b6d12a8fa447.png">
<img width="240" alt="image" src="https://user-images.githubusercontent.com/23568201/221830664-d1e11ee1-4915-4d02-82bd-cb676d2c0784.png">

**Comment by marunrun** [comment]
emm 我这边m1是没有问题的。

你可以尝试下载源码 自行构建一下, 可以参考 [tauri](https://github.com/tauri-apps/tauri)
```shell
git clone https://github.com/marunrun/showstart-checkout.git
cd showstart-checkout 
pnpm install
pnpm tauri build
```

**Comment by sheng3233836** [comment]
需要一些什么环境嘛，typescript相关环境我都没有
