### ISSUE TITLE
error Frequent requests, please wait

### ISSUE THREAD

**Issue by weightwater** [marunrun/showstart-checkout#40]
我是用的是macbook pro 2021 M1，在使用捡漏功能时经常会出现如下提示，这是因为我频繁进行请求，秀动后台对我的限制吗？大家有这种现象吗？
error Frequent requests, please wait

**Comment by marunrun** [comment]
> 我是用的是macbook pro 2021 M1，在使用捡漏功能时经常会出现如下提示，这是因为我频繁进行请求，秀动后台对我的限制吗？大家有这种现象吗？
> 
> error Frequent requests, please wait


应该是秀动的提示
