### ISSUE TITLE
大佬有没有机会等你更新定时抢票呀

### ISSUE THREAD

**Issue by Yiihaoo** [marunrun/showstart-checkout#46]

**Comment by marunrun** [comment]
更新什么定时抢票 。

我已经忘记这个代码咋写的了，最近比较沉迷打游戏🤪

**Comment by marunrun** [comment]
什么样子的定时抢票，定时好像是有的吧。

p.s. 我已经忘记这个代码咋写的了，然后最近比较沉迷打游戏🤪

**Comment by Yiihaoo** [comment]
有定时抢票，但是一开启临近抢票就会卡住所以用不了哈哈哈，期待能更新到更好用，请大佬喝咖啡
（不想更也没关系，能捡漏已经比手动抢好多了！）

**Comment by Yiihaoo** [comment]
昨天测试没有问题，但刚刚捡漏失败了，提示“下单异常，请更新至app最新版本 order026”

**Comment by marunrun** [comment]
> 昨天测试没有问题，但刚刚捡漏失败了，提示“下单异常，请更新至app最新版本 order026”

可能秀动更新了app
