### ISSUE TITLE
多账号使用问题

### ISSUE THREAD

**Issue by Yancey597** [marunrun/showstart-checkout#8]
你好，如果使用多账号是不是只需要复制项目文件夹然后多次执行checkout.exe

**Comment by Yancey597** [comment]
还有定时抢票如何操作，界面没有提供选择时间的地方
![image](https://user-images.githubusercontent.com/46004197/176503262-156b6e98-ada1-40fb-8bcb-ee496cff2f93.png)

**Comment by marunrun** [comment]
多账号使用 需要复制多个项目文件夹出来即可。 但多账号同时抢票会出现下单限流，因为秀动对于ip有限制。

定时抢票取的是对应演出的开票时间，我感觉设置时间没有太大的用处就去掉了。

**Comment by Yancey597** [comment]
好的，谢谢

**Comment by Yancey597** [comment]
有新问题，点击捡漏提示还未开票，然后便自动停止
![image](https://user-images.githubusercontent.com/46004197/176594050-5b5bcd55-09db-46d0-a142-3235aa92fff5.png)

**Comment by Yancey597** [comment]
![image](https://user-images.githubusercontent.com/46004197/176609301-b2e69d05-495d-4b9d-8161-ac24384b0387.png)
新问题，捡漏貌似不起作用还出异常

**Comment by Yancey597** [comment]
![image](https://user-images.githubusercontent.com/46004197/176609443-6abd3265-70fb-493b-abc2-69d90dfd3df9.png)

**Comment by marunrun** [comment]
> ![image](https://user-images.githubusercontent.com/46004197/176609301-b2e69d05-495d-4b9d-8161-ac24384b0387.png) 新问题，捡漏貌似不起作用还出异常

 这个估计是秀动服务异常, 暂时在我这里没有复现.

捡漏已经加了开票状态的判断
