### ISSUE TITLE
捡漏自动停止问题

### ISSUE THREAD

**Issue by Redlove2015** [marunrun/showstart-checkout#9]
有时候捡漏慢了出现库存不足的提示，就自动停止捡漏了请问能否更新捡漏失败继续自动捡漏以及win10系统通知功能呢？谢谢！

**Comment by marunrun** [comment]
> 有时候捡漏慢了出现库存不足的提示，就自动停止捡漏了请问能否更新捡漏失败继续自动捡漏以及win10系统通知功能呢？谢谢！

有空的话 我会更新的
